Repository comixed/comixed, pull requests merged in 2019-11, with the labels that each got.

#58 [BUILD] Bumped maven-git-code-format to v1.37
  pom.xml
Labels: build

#61 Clean up the Google Java format plugin configuration.
  pom.xml
Labels: build

#55 maven github action
  .github/workflows/maven.yml
Labels: build

#56 [CLEANUP] Apply google java format to comixed-importer and include it…
  comixed-importer/src/main/java/org/comixed/ComiXedImporterApp.java
  comixed-importer/src/main/java/org/comixed/importer/ComiXedImporterConfig.java
  comixed-importer/src/main/java/org/comixed/importer/ImportFileProcessor.java
  comixed-importer/src/main/java/org/comixed/importer/PathReplacement.java
  comixed-importer/src/main/java/org/comixed/importer/ProcessorException.java
  comixed-importer/src/main/java/org/comixed/importer/adaptors/ComicFileImportAdaptor.java
  comixed-importer/src/main/java/org/comixed/importer/adaptors/ComicRackBackupAdaptor.java
  comixed-importer/src/main/java/org/comixed/importer/adaptors/ImportAdaptorException.java
  comixed-importer/src/test/java/org/comixed/importer/ImportFileProcessorTest.java
  comixed-importer/src/test/java/org/comixed/importer/PathReplacementTest.java
  comixed-importer/src/test/java/org/comixed/importer/adaptors/ComicFileImportAdaptorTest.java
  comixed-importer/src/test/java/org/comixed/importer/adaptors/ComicRackBackupAdaptorTest.java
  pom.xml
Labels: build

#62 [Issue #60] Publish the build artifact to Github.
  .github/workflows/development.yml
  .github/workflows/maven.yml
  .gitlab-ci.yml
  .travis.yml
  README.md
  comixed-app/pom.xml
  comixed-app/src/main/assembly/src.xml
Labels: build

#73 [Issue #68] Rollback maven-git-code-format to 1.36.
  pom.xml
Labels: bug, build

#65 [Issue #57] - Imports manual lists from comicrack database into comixed
  comixed-importer/pom.xml
  comixed-importer/src/main/java/org/comixed/ComiXedImporterApp.java
  comixed-importer/src/main/java/org/comixed/importer/ImportFileProcessor.java
  comixed-importer/src/main/java/org/comixed/importer/adaptors/ComicFileImportAdaptor.java
  comixed-importer/src/main/java/org/comixed/importer/adaptors/ComicRackBackupAdaptor.java
  comixed-importer/src/test/java/org/comixed/importer/ImportFileProcessorTest.java
  comixed-importer/src/test/java/org/comixed/importer/adaptors/ComicRackBackupAdaptorTest.java
  comixed-importer/src/test/resources/comicrack-backup.xml
Labels: importing

#74 [BUILD] Enable SonarCloud analysis of the Java codebase.
  .github/workflows/sonarcloud-analysis.yml
  pom.xml
Labels: build, enhancement
