Repository comixed/comixed, pull requests merged in 2020-08, with the labels that each got.

#453 Added option to delete original comic when converting comics [184]
  comixed-frontend/src/app/library/actions/library.actions.ts
  comixed-frontend/src/app/library/adaptors/library.adaptor.spec.ts
  comixed-frontend/src/app/library/adaptors/library.adaptor.ts
  comixed-frontend/src/app/library/components/convert-comics-settings/convert-comics-settings.component.html
  comixed-frontend/src/app/library/components/convert-comics-settings/convert-comics-settings.component.ts
  comixed-frontend/src/app/library/effects/library.effects.spec.ts
  comixed-frontend/src/app/library/effects/library.effects.ts
  comixed-frontend/src/app/library/reducers/library.reducer.spec.ts
  comixed-frontend/src/app/library/services/library.service.spec.ts
  comixed-frontend/src/app/library/services/library.service.ts
  comixed-frontend/src/assets/i18n/en/library.json
  comixed-frontend/src/assets/i18n/es/library.json
  comixed-frontend/src/assets/i18n/fr/library.json
  comixed-frontend/src/assets/i18n/pt/library.json
  comixed-model/src/main/java/org/comixedproject/model/comic/Comic.java
  comixed-rest-api/src/main/java/org/comixedproject/controller/library/LibraryController.java
  comixed-rest-api/src/main/java/org/comixedproject/net/ConvertComicsRequest.java
  comixed-rest-api/src/test/java/org/comixedproject/controller/library/LibraryControllerTest.java
  comixed-services/src/main/java/org/comixedproject/service/library/LibraryService.java
  comixed-services/src/test/java/org/comixedproject/service/library/LibraryServiceTest.java
  comixed-tasks/src/main/java/org/comixedproject/task/encoders/ConvertComicTaskEncoder.java
  comixed-tasks/src/main/java/org/comixedproject/task/model/ConvertComicWorkerTask.java
  comixed-tasks/src/main/java/org/comixedproject/task/model/ConvertComicsWorkerTask.java
  comixed-tasks/src/test/java/org/comixedproject/task/encoders/ConvertComicTaskEncoderTest.java
  comixed-tasks/src/test/java/org/comixedproject/task/model/ConvertComicWorkerTaskTest.java
  comixed-tasks/src/test/java/org/comixedproject/task/model/ConvertComicsWorkerTaskTest.java
Labels: enhancement

#455 Changed git-commit-id-plugin configuration
  comixed-app/pom.xml
  comixed-app/src/main/resources/build-details.properties
  comixed-frontend/src/assets/i18n/en/backend-status.json
  comixed-frontend/src/assets/i18n/es/backend-status.json
  comixed-frontend/src/assets/i18n/fr/backend-status.json
  comixed-frontend/src/assets/i18n/pt/backend-status.json
  comixed-services/src/main/java/org/comixedproject/service/core/DetailsService.java
Labels: enhancement

#457 Added styling to hilight deleted page rows [#445]
  comixed-frontend/src/app/comics/components/comic-pages/comic-pages.component.html
  comixed-frontend/src/app/comics/components/comic-pages/comic-pages.component.scss
  comixed-frontend/src/colors.scss
Labels: enhancement

#467 Added the JDBC URL to the build details [#408]
  comixed-frontend/src/app/backend-status/models/build-details.fixtures.ts
  comixed-frontend/src/app/backend-status/models/build-details.ts
  comixed-frontend/src/app/backend-status/pages/build-details-page/build-details-page.component.html
  comixed-frontend/src/assets/i18n/en/backend-status.json
  comixed-frontend/src/assets/i18n/es/backend-status.json
  comixed-frontend/src/assets/i18n/fr/backend-status.json
  comixed-frontend/src/assets/i18n/pt/backend-status.json
  comixed-model/src/main/java/org/comixedproject/model/core/BuildDetails.java
  comixed-services/src/main/java/org/comixedproject/service/core/DetailsService.java
Labels: enhancement

#486 Fixed loading task audit log entries [#468]
  comixed-frontend/src/app/backend-status/actions/load-task-audit-log.actions.ts
  comixed-frontend/src/app/backend-status/pages/task-audit-log-page/task-audit-log-page.component.html
  comixed-frontend/src/app/backend-status/pages/task-audit-log-page/task-audit-log-page.component.spec.ts
  comixed-frontend/src/app/backend-status/pages/task-audit-log-page/task-audit-log-page.component.ts
  comixed-frontend/src/app/backend-status/reducers/load-task-audit-log.reducer.spec.ts
  comixed-frontend/src/app/backend-status/reducers/load-task-audit-log.reducer.ts
  comixed-rest-api/src/main/java/org/comixedproject/controller/core/AuditLogController.java
Labels: bugfix

#489 Changed user preferences to use true/false instead of 1/0 [#387]
  comixed-frontend/src/app/library/components/consolidate-library/consolidate-library.component.spec.ts
  comixed-frontend/src/app/library/components/consolidate-library/consolidate-library.component.ts
  comixed-frontend/src/app/user/adaptors/library-display.adaptor.ts
Labels: feature

#494 Added removing deleted comics during library consolidation [#393]
  comixed-tasks/src/main/java/org/comixedproject/task/model/MoveComicsWorkerTask.java
  comixed-tasks/src/test/java/org/comixedproject/task/model/MoveComicsWorkerTaskTest.java
Labels: enhancement

#492 Changed where and when the persisted task is deleted [#487]
  comixed-tasks/src/main/java/org/comixedproject/task/encoders/AbstractWorkerTaskEncoder.java
  comixed-tasks/src/main/java/org/comixedproject/task/encoders/AddComicWorkerTaskEncoder.java
  comixed-tasks/src/main/java/org/comixedproject/task/encoders/DeleteComicWorkerTaskEncoder.java
  comixed-tasks/src/main/java/org/comixedproject/task/encoders/ProcessComicWorkerTaskEncoder.java
  comixed-tasks/src/main/java/org/comixedproject/task/model/DeleteComicWorkerTask.java
  comixed-tasks/src/main/java/org/comixedproject/task/model/MonitorTaskQueueWorkerTask.java
  comixed-tasks/src/main/java/org/comixedproject/task/runner/TaskManager.java
  comixed-tasks/src/test/java/org/comixedproject/task/encoders/AddComicWorkerTaskEncoderTest.java
  comixed-tasks/src/test/java/org/comixedproject/task/encoders/DeleteComicWorkerTaskEncoderTest.java
  comixed-tasks/src/test/java/org/comixedproject/task/encoders/ProcessComicWorkerWorkerTaskEncoderTest.java
  comixed-tasks/src/test/java/org/comixedproject/task/model/MonitorTaskQueueWorkerTaskTest.java
  comixed-tasks/src/test/java/org/comixedproject/task/runner/TaskManagerTest.java
Labels: enhancement
