Repository comixed/comixed, pull requests merged in 2022-07, with the labels that each got.

#1342 Added French translation version 1.1 [#1336]
  comixed-webui/src/assets/i18n/fr/admin.json
  comixed-webui/src/assets/i18n/fr/app.json
  comixed-webui/src/assets/i18n/fr/comic-books.json
  comixed-webui/src/assets/i18n/fr/comic-files.json
  comixed-webui/src/assets/i18n/fr/comic-metadata.json
  comixed-webui/src/assets/i18n/fr/library.json
Labels: enhancement

#1351 Fixed rescanning comics failed to complete [#1349]
  comixed-adaptors/src/main/java/org/comixedproject/adaptors/comicbooks/ComicBookAdaptor.java
  comixed-batch/src/main/java/org/comixedproject/batch/comicbooks/processors/LoadFileDetailsProcessor.java
  comixed-batch/src/test/java/org/comixedproject/batch/comicbooks/processors/LoadFileDetailsProcessorTest.java
Labels: bugfix

#1352 Fixed show both delete and undelete buttons for a comic [#1344]
  comixed-webui/src/app/comic-books/pages/comic-book-page/comic-book-page.component.html
Labels: bugfix

#1353 Added showing comics as unprocessed based on state [#1347]
  comixed-webui/src/app/comic-books/reducers/comic-book-list.reducer.ts
Labels: enhancement

#1354 Added clearing selections are starting a rescan [#1350]
  comixed-webui/src/app/library/actions/library.actions.ts
  comixed-webui/src/app/library/effects/rescan-comics.effects.spec.ts
  comixed-webui/src/app/library/effects/rescan-comics.effects.ts
  comixed-webui/src/app/library/reducers/library.reducer.spec.ts
  comixed-webui/src/app/library/reducers/library.reducer.ts
Labels: enhancement

#1356 Fixed clearing selections after setting comic deleted state [#1340]
  comixed-webui/src/app/comic-books/effects/mark-comics-deleted.effects.spec.ts
  comixed-webui/src/app/comic-books/effects/mark-comics-deleted.effects.ts
Labels: bugfix

#1361 Changed the expected exception for the batch processes [#1360]
  comixed-batch/src/main/java/org/comixedproject/batch/comicbooks/processors/CreateMetadataSourceProcessor.java
Labels: bugfix

#1363 Fixed when creating an OPDS id for a null value [#1362]
  comixed-repositories/src/main/java/org/comixedproject/repositories/comicbooks/ComicBookRepository.java
  comixed-services/src/main/java/org/comixedproject/service/comicbooks/ComicBookService.java
  comixed-services/src/test/java/org/comixedproject/service/comicbooks/ComicBookServiceTest.java
Labels: bugfix

#1370 Fixed sorting the blocked page list [#1368]
  comixed-webui/src/app/comic-pages/pages/blocked-hash-list-page/blocked-hash-list-page.component.html
  comixed-webui/src/app/comic-pages/pages/blocked-hash-list-page/blocked-hash-list-page.component.spec.ts
  comixed-webui/src/app/comic-pages/pages/blocked-hash-list-page/blocked-hash-list-page.component.ts
Labels: bugfix

#1371 Fixed showing block and unblock buttons on duplicate page view [#1365]
  comixed-webui/src/app/library/pages/duplicate-page-detail-page/duplicate-page-detail-page.component.html
  comixed-webui/src/app/library/pages/duplicate-page-detail-page/duplicate-page-detail-page.component.spec.ts
  comixed-webui/src/app/library/pages/duplicate-page-detail-page/duplicate-page-detail-page.component.ts
Labels: bugfix

#1372 Fixed the block duplicate page confirmation message and title [#1365]
  comixed-webui/src/assets/i18n/de/library.json
  comixed-webui/src/assets/i18n/en/library.json
  comixed-webui/src/assets/i18n/pt/library.json
Labels: bugfix

#1378 Fixed import reshowing imported comics on Windows [#1373]
  comixed-batch/src/test/java/org/comixedproject/batch/comicbooks/processors/MoveComicBookProcessorTest.java
  comixed-services/src/main/java/org/comixedproject/service/comicfiles/ComicFileService.java
  comixed-services/src/test/java/org/comixedproject/service/comicfiles/ComicFileServiceTest.java
Labels: critical, bugfix

#1364 Added loading the library state as a single request [#1284]
  comixed-model/src/main/java/org/comixedproject/model/net/library/LibrarySegmentState.java
  comixed-model/src/main/java/org/comixedproject/model/net/library/LibraryState.java
  comixed-model/src/main/java/org/comixedproject/model/net/library/SetComicsReadRequest.java
  comixed-model/src/main/java/org/comixedproject/views/View.java
  comixed-repositories/src/main/java/org/comixedproject/repositories/comicbooks/ComicBookRepository.java
  comixed-repositories/src/test/java/org/comixedproject/repositories/comicbooks/ComicBookRepositoryTest.java
  comixed-rest/src/main/java/org/comixedproject/rest/library/LastReadController.java
  comixed-rest/src/main/java/org/comixedproject/rest/library/LibraryController.java
  comixed-rest/src/test/java/org/comixedproject/rest/library/LastReadControllerTest.java
  comixed-rest/src/test/java/org/comixedproject/rest/library/LibraryControllerTest.java
  comixed-services/src/main/java/org/comixedproject/service/comicbooks/ComicBookService.java
  comixed-services/src/main/java/org/comixedproject/service/library/LibraryStateService.java
  comixed-services/src/test/java/org/comixedproject/service/comicbooks/ComicBookServiceTest.java
  comixed-services/src/test/java/org/comixedproject/service/library/LibraryStateServiceTest.java
  comixed-webui/src/app/app.component.ts
  comixed-webui/src/app/library/actions/library.actions.ts
  comixed-webui/src/app/library/effects/library.effects.spec.ts
  comixed-webui/src/app/library/effects/library.effects.ts
  comixed-webui/src/app/library/library.constants.ts
  comixed-webui/src/app/library/models/net/library-segment-state.ts
  comixed-webui/src/app/library/models/net/library-state.ts
  comixed-webui/src/app/library/reducers/library.reducer.spec.ts
  comixed-webui/src/app/library/reducers/library.reducer.ts
  comixed-webui/src/app/library/selectors/library.selectors.spec.ts
  comixed-webui/src/app/library/services/library.service.spec.ts
  comixed-webui/src/app/library/services/library.service.ts
  comixed-webui/src/assets/i18n/de/library.json
  comixed-webui/src/assets/i18n/en/library.json
  comixed-webui/src/assets/i18n/es/library.json
  comixed-webui/src/assets/i18n/fr/library.json
  comixed-webui/src/assets/i18n/pt/library.json
Labels: enhancement, library, state

#1384 Changed the home page to use remote library statistics [#1381]
  comixed-webui/src/app/components/collections-chart/collections-chart.component.html
  comixed-webui/src/app/components/collections-chart/collections-chart.component.spec.ts
  comixed-webui/src/app/components/collections-chart/collections-chart.component.ts
  comixed-webui/src/app/components/comic-state-chart/comic-state-chart.component.html
  comixed-webui/src/app/components/comic-state-chart/comic-state-chart.component.spec.ts
  comixed-webui/src/app/components/comic-state-chart/comic-state-chart.component.ts
  comixed-webui/src/app/components/comics-by-year-chart/comics-by-year-chart.component.html
  comixed-webui/src/app/components/comics-by-year-chart/comics-by-year-chart.component.spec.ts
  comixed-webui/src/app/components/comics-by-year-chart/comics-by-year-chart.component.ts
  comixed-webui/src/app/components/read-comics-chart/read-comics-chart.component.html
  comixed-webui/src/app/components/read-comics-chart/read-comics-chart.component.spec.ts
  comixed-webui/src/app/components/read-comics-chart/read-comics-chart.component.ts
  comixed-webui/src/app/library/actions/library.actions.ts
  comixed-webui/src/app/library/effects/library.effects.spec.ts
  comixed-webui/src/app/library/effects/library.effects.ts
  comixed-webui/src/app/library/models/net/remote-library-segment-state.ts
  comixed-webui/src/app/library/models/net/remote-library-state.ts
  comixed-webui/src/app/library/reducers/library.reducer.spec.ts
  comixed-webui/src/app/library/reducers/library.reducer.ts
  comixed-webui/src/app/library/selectors/library.selectors.spec.ts
  comixed-webui/src/app/library/services/library.service.spec.ts
  comixed-webui/src/app/pages/home/home.component.html
  comixed-webui/src/app/pages/home/home.component.ts
Labels: enhancement

#1386 Changed the side nav bar to use the new library state [#1383]
  comixed-webui/src/app/components/side-navigation/side-navigation.component.spec.ts
  comixed-webui/src/app/components/side-navigation/side-navigation.component.ts
Labels: enhancement

#1387 Removed the busy overlay from the home page [#1381]
  comixed-webui/src/app/components/side-navigation/side-navigation.component.html
  comixed-webui/src/app/pages/home/home.component.html
  comixed-webui/src/assets/i18n/de/app.json
  comixed-webui/src/assets/i18n/en/app.json
  comixed-webui/src/assets/i18n/es/app.json
  comixed-webui/src/assets/i18n/fr/app.json
  comixed-webui/src/assets/i18n/pt/app.json
Labels: enhancement

#1388 Added filtering duplicate pages to show only blocked entries [#1358]
  comixed-webui/src/app/library/library.constants.ts
  comixed-webui/src/app/library/pages/duplicate-page-list-page/duplicate-page-list-page.component.html
  comixed-webui/src/app/library/pages/duplicate-page-list-page/duplicate-page-list-page.component.spec.ts
  comixed-webui/src/app/library/pages/duplicate-page-list-page/duplicate-page-list-page.component.ts
  comixed-webui/src/assets/i18n/de/library.json
  comixed-webui/src/assets/i18n/en/library.json
  comixed-webui/src/assets/i18n/es/library.json
  comixed-webui/src/assets/i18n/fr/library.json
  comixed-webui/src/assets/i18n/pt/library.json
Labels: enhancement
